# Generated by Django 3.2.11 on 2022-01-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
