# Generated by Django 3.2.11 on 2022-01-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
